//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookWeights
    {
        public int Id { get; set; }
        public string BookName { get; set; }
        public string BookWeight { get; set; }
        public string PostalCharges { get; set; }
    }
}
