//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities
    {
        public Cities()
        {
            this.DistributoresAndDealers = new HashSet<DistributoresAndDealers>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> DistrictId { get; set; }
    
        public virtual Districts Districts { get; set; }
        public virtual ICollection<DistributoresAndDealers> DistributoresAndDealers { get; set; }
    }
}
