//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSRCategories
    {
        public CSRCategories()
        {
            this.CSR = new HashSet<CSR>();
        }
    
        public int CSRCategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<CSR> CSR { get; set; }
    }
}
