//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorInventoryMovement
    {
        public DistributorInventoryMovement()
        {
            this.DistributorInventoryMovementDetails = new HashSet<DistributorInventoryMovementDetails>();
        }
    
        public int DistributorInventoryMovementId { get; set; }
        public Nullable<int> FromDistributorId { get; set; }
        public Nullable<int> ToDistributorId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsAdminApprove { get; set; }
    
        public virtual ICollection<DistributorInventoryMovementDetails> DistributorInventoryMovementDetails { get; set; }
    }
}
