//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Districts
    {
        public Districts()
        {
            this.Cities = new HashSet<Cities>();
            this.TempShippingAddress = new HashSet<TempShippingAddress>();
            this.Users = new HashSet<Users>();
        }
    
        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual ICollection<Cities> Cities { get; set; }
        public virtual States States { get; set; }
        public virtual ICollection<TempShippingAddress> TempShippingAddress { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
