//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorInventoryMovementDetails
    {
        public int DistributorInventoryMovementDetailId { get; set; }
        public Nullable<int> DistributorInventoryMovementId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> NoOfInventoryItems { get; set; }
    
        public virtual DistributorInventoryMovement DistributorInventoryMovement { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
