//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class eBooks
    {
        public eBooks()
        {
            this.eReaderSubscriptionDetails = new HashSet<eReaderSubscriptionDetails>();
            this.TempeReaderSubscriptionDetails = new HashSet<TempeReaderSubscriptionDetails>();
        }
    
        public int eBookId { get; set; }
        public string eBookTitle { get; set; }
        public string eBookImage { get; set; }
        public string eBookTOC { get; set; }
        public string eBookFolder { get; set; }
        public Nullable<decimal> eBookPrice { get; set; }
        public Nullable<int> ValidMonths { get; set; }
        public Nullable<int> InventoryCategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> InventoryId { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual InventoryCategories InventoryCategories { get; set; }
        public virtual ICollection<eReaderSubscriptionDetails> eReaderSubscriptionDetails { get; set; }
        public virtual ICollection<TempeReaderSubscriptionDetails> TempeReaderSubscriptionDetails { get; set; }
    }
}
