//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryRequestDetails
    {
        public int InventoryRequestDetailId { get; set; }
        public Nullable<int> InventoryRequestId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> SaleQuantity { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsPackage { get; set; }
        public string BatchId { get; set; }
        public Nullable<int> ReturnQuantity { get; set; }
        public Nullable<int> DamagedQuantity { get; set; }
    }
}
