//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryRequests
    {
        public InventoryRequests()
        {
            this.InventoryDamageStock = new HashSet<InventoryDamageStock>();
            this.InventoryReturns = new HashSet<InventoryReturns>();
            this.RequestPaymentDetails = new HashSet<RequestPaymentDetails>();
        }
    
        public int InventoryRequestId { get; set; }
        public Nullable<int> DistributorOrDealerId { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<bool> IsPackage { get; set; }
    
        public virtual ICollection<InventoryDamageStock> InventoryDamageStock { get; set; }
        public virtual ICollection<InventoryReturns> InventoryReturns { get; set; }
        public virtual ICollection<RequestPaymentDetails> RequestPaymentDetails { get; set; }
    }
}
