//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryDamageStock
    {
        public InventoryDamageStock()
        {
            this.DamageStockPaymentDetails = new HashSet<DamageStockPaymentDetails>();
        }
    
        public int InventoryDamageStockId { get; set; }
        public Nullable<int> DistributorOrDealerId { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<bool> IsPackage { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> InventoryRequestId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<bool> PaymentReceived { get; set; }
    
        public virtual ICollection<DamageStockPaymentDetails> DamageStockPaymentDetails { get; set; }
        public virtual InventoryRequests InventoryRequests { get; set; }
    }
}
