//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCategories
    {
        public InventoryCategories()
        {
            this.eBooks = new HashSet<eBooks>();
            this.Inventory = new HashSet<Inventory>();
        }
    
        public int InventoryCategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> InventoryTypeId { get; set; }
    
        public virtual ICollection<eBooks> eBooks { get; set; }
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual InventoryTypes InventoryTypes { get; set; }
    }
}
