//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventorySales
    {
        public int InventorySaleId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> DistributorOrDealerId { get; set; }
        public Nullable<int> NoOfInventoryItems { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual DistributoresAndDealers DistributoresAndDealers { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
