//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packages
    {
        public Packages()
        {
            this.PackageDetails = new HashSet<PackageDetails>();
        }
    
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public Nullable<int> InventoryTypeId { get; set; }
        public Nullable<int> InventoryCategoryId { get; set; }
        public decimal PackageDiscount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PackageImage { get; set; }
        public string Description { get; set; }
        public Nullable<int> NoOfPackages { get; set; }
    
        public virtual ICollection<PackageDetails> PackageDetails { get; set; }
    }
}
