//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageDetails
    {
        public int PackageDetailId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string BatchId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Packages Packages { get; set; }
    }
}
