//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayuInputParameters
    {
        public int PayuInputParameterId { get; set; }
        public string HashParameters { get; set; }
        public string Hash { get; set; }
        public string PostForm { get; set; }
        public Nullable<bool> SessionExists { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
