//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayuOutputParameters
    {
        public int PayuOutputParameterId { get; set; }
        public string Hash { get; set; }
        public string ReverseHash { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsSessionExists { get; set; }
        public string TransactionId { get; set; }
        public string MIHPayId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
