//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrders
    {
        public PurchaseOrders()
        {
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetails>();
        }
    
        public int PurchaseOrderId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PurchaseOrdersStatus { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<PurchaseOrderDetails> PurchaseOrderDetails { get; set; }
    }
}
