//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class States
    {
        public States()
        {
            this.Districts = new HashSet<Districts>();
            this.TempShippingAddress = new HashSet<TempShippingAddress>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<Districts> Districts { get; set; }
        public virtual ICollection<TempShippingAddress> TempShippingAddress { get; set; }
    }
}
