//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribers
    {
        public Subscribers()
        {
            this.eReaderSubscriptionDetails = new HashSet<eReaderSubscriptionDetails>();
            this.MagazineDeliveryDetails = new HashSet<MagazineDeliveryDetails>();
            this.SubscriptionDetails = new HashSet<SubscriptionDetails>();
            this.TempeReaderSubscriptionDetails = new HashSet<TempeReaderSubscriptionDetails>();
            this.TempSubscriptionDetails = new HashSet<TempSubscriptionDetails>();
        }
    
        public int SubscriberId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ModeId { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsUser { get; set; }
    
        public virtual ICollection<eReaderSubscriptionDetails> eReaderSubscriptionDetails { get; set; }
        public virtual ICollection<MagazineDeliveryDetails> MagazineDeliveryDetails { get; set; }
        public virtual SubscriptionMode SubscriptionMode { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<SubscriptionDetails> SubscriptionDetails { get; set; }
        public virtual ICollection<TempeReaderSubscriptionDetails> TempeReaderSubscriptionDetails { get; set; }
        public virtual ICollection<TempSubscriptionDetails> TempSubscriptionDetails { get; set; }
    }
}
