//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionMode
    {
        public SubscriptionMode()
        {
            this.Subscribers = new HashSet<Subscribers>();
            this.SubscriptionAmount = new HashSet<SubscriptionAmount>();
        }
    
        public int ModeId { get; set; }
        public string ModeType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Subscribers> Subscribers { get; set; }
        public virtual ICollection<SubscriptionAmount> SubscriptionAmount { get; set; }
    }
}
