//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempUserOrderDetails
    {
        public int TempUserOrderDetailId { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<int> TempUserOrderId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual TempUserOrders TempUserOrders { get; set; }
    }
}
