//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrders
    {
        public UserOrders()
        {
            this.UserOrderDetails = new HashSet<UserOrderDetails>();
            this.UserShippingAddress = new HashSet<UserShippingAddress>();
        }
    
        public int UserOrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<int> CourierId { get; set; }
        public string TrackNo { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> DispatchedDate { get; set; }
        public Nullable<decimal> ShippingCharges { get; set; }
    
        public virtual Couriers Couriers { get; set; }
        public virtual ICollection<UserOrderDetails> UserOrderDetails { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<UserShippingAddress> UserShippingAddress { get; set; }
    }
}
