//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSFWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Subscribers = new HashSet<Subscribers>();
            this.TempeReaderSubscriptionDetails = new HashSet<TempeReaderSubscriptionDetails>();
            this.TempShippingAddress = new HashSet<TempShippingAddress>();
            this.TempSubscriptionDetails = new HashSet<TempSubscriptionDetails>();
            this.TempUserOrders = new HashSet<TempUserOrders>();
            this.UserComments = new HashSet<UserComments>();
            this.UserOrders = new HashSet<UserOrders>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string City { get; set; }
        public Nullable<int> PinCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Profession { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsSubscribeDailyQuotes { get; set; }
        public Nullable<bool> IsSubscribeNewPackagesalert { get; set; }
        public Nullable<bool> IsSubscribeNewsAndArticles { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<bool> MailActivation { get; set; }
    
        public virtual Districts Districts { get; set; }
        public virtual ICollection<Subscribers> Subscribers { get; set; }
        public virtual ICollection<TempeReaderSubscriptionDetails> TempeReaderSubscriptionDetails { get; set; }
        public virtual ICollection<TempShippingAddress> TempShippingAddress { get; set; }
        public virtual ICollection<TempSubscriptionDetails> TempSubscriptionDetails { get; set; }
        public virtual ICollection<TempUserOrders> TempUserOrders { get; set; }
        public virtual ICollection<UserComments> UserComments { get; set; }
        public virtual ICollection<UserOrders> UserOrders { get; set; }
    }
}
